### ISSUE TITLE
Search results relevancy / sorting

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#132]
Probably a number of enhancements can be made here, but one that seems pretty obvious it searching for two words. Would it be possible to show first packages that contain both words?

For example, ["http proxy"](https://atmospherejs.com/?q=http%20proxy) returns, among others, the **moment** package, which deals with neither http or proxies, but has "http://momentjs.com" on its page. The only package that does contain both words, [http-more](https://atmospherejs.com/package/http-more) is buried somewhere among the 3rd row of results.

Disclaimer: I'm the author of http-more.

**Comment by tmeasday** [comment]
We've got a future feature of using a full fledged relevancy based text index. In the meantime we're just using mongo and text matching, sorting via atmosphere score.

Do you have any idea of how we could use mongo to do a more nuanced order? My mongo-fu isn't really very well developed but I fear there's no real way to do what you are asking..

**Comment by splendido** [comment]
This is not about 'two words search' but the title seems related enough to prevent me to create a new issue...

I'm feeling there's something weird on sorting.
For example if you look [here](https://atmospherejs.com/useraccounts/bootstrap) you'll see a package with almost 200 'app installs', seven stars...
...and no '100' milestone on the history nor tendency graph ;-)

If you look [here](https://atmospherejs.com/useraccounts/famous-wrapper) you'll see another package, with less than 20 app installs, one star...
...and no tendency graph

If you [go search](https://atmospherejs.com/?q=accounts) for 'accounts' and click on more you'll ses the second one at the 26th position (more or less)
if you then click on more four more times (while looking at already loaded packages changing their position, which is really annoying...) you'll find the first one at the 105th position (more or less....)

While [this](https://atmospherejs.com/useraccounts/core), which stands out at position 115, has six stars and about 53 app installs...
...and no tendency graph! ;-)

So the question is: why is this happening? Why the first one stands out as 'better' the the other two?
My guess is that the only reason could be something related to the analysis of open/closed issues on the respective github repo...
Could it be?

The third package is heavily maintained, issues are being opened and very quickly closed because there are people using its dependant packages and helping make them better.

I'm not pretending they should appear higher in the list (even if IMHO I partly think of it...), but I'm asking why the second one is appearing before the other two: there's apparently no reason for this.

Could you shed some light on the reasons behind this?

Disclaimer: I'm the maintainer of all three packages ;-)

**Comment by dandv** [comment]
Well, I _think_ it's a bug, but I _hope_ it's the same sort of randomization algorithm that Quora uses to give answers other than the best ones more chance of being read and upvoted. Otherwise, the "best" items keep getting more votes, at the detriment of newcomers.

**Comment by splendido** [comment]
Ok, today everything seems different from yesterday...
Now graphs are there and almost all packages from useraccounts show up in the top 20!

![atmosphere_useraccounts_top20](https://cloud.githubusercontent.com/assets/6148980/5163761/a3df8a1e-73cf-11e4-96df-bcc5e383dcef.png)

perhaps something changed behind the scenes?

**Comment by tmeasday** [comment]
Hey @splendido - yes there was a problem with the scoring job and it hadn't been scoring every package for a little while. This is sorted out now as you can see. Thanks for pointing this out.

@dandv - I'm not really sure that same logic applies to packages where there's less scope to feed back on the package directly on Atmosphere, and less of a need to 'explore' and fill out unknown packages. But it could be something to look at later.

**Comment by splendido** [comment]
Hi Tom,
I'm happy I could help figuring it out.
Thanks for the great job!

**Comment by dandv** [comment]
Looks like we still have some issues with search ranking for ["moment"](https://atmospherejs.com/?q=moment):

![image](https://cloud.githubusercontent.com/assets/33569/5237437/249fb194-7838-11e4-9549-6003931350cd.png)

The official package has 3 stars and 2 app installs, but shows up after packages with 0 stars and 3 app installs (ryzmek:moment-locale-fr). The ranking surely doesn't care that much about 1 extra app installs, because leesangwon:moment and gildaspk:moment-datepicker both have zero stars, but leesangwon's shows before gilda's despite having only 5 vs. 34 app installs.

**Comment by tmeasday** [comment]
@dandv (I think) we just need to wait for the new score for this package to be calculated. The scoring happens nightly at 7am UTC (11pm PST right now I think). And the score is calculated based on the start of the day. So, based on the fact that the package was published only 35 hours ago and the scoring is going to run again in around 8 hours, I'd say none of it's installs were counted during the last scoring.

Let's check again tomorrow :)

I starred the package if that helps ;)

**Comment by dandv** [comment]
Thanks Tom, didn't know about the cron job timings.

Still, https://atmospherejs.com/gildaspk/moment-languages shows before https://atmospherejs.com/gildaspk/moment-datepicker, and they both have 0 stars, but the former has 7 fewer installs.

**Comment by tmeasday** [comment]
Hey Dan, yes but the former also hasn't published a new version in quite some time. As explained [here](http://blog.percolatestudio.com/engineering/atmosphere-score/) (still mostly up to date, although not factoring in flagging/starring), we try to take age into account to encourage newer packages.

**Comment by zol** [comment]
No longer a serious issue I think.
