### ISSUE TITLE
Don't word-wrap <pre>

### ISSUE THREAD

**Issue by lirbank** [percolatestudio/atmosphere#141]
Hey, 

(In Chrome,) it would be great if you didn't word-wrap the code examples. Look at my examples on [accounts-merge](https://atmospherejs.com/package/accounts-merge). Too looong lines, my bad, but still it looks ok [on Github](https://github.com/lirbank/meteor-accounts-merge/).

Solution:

```
pre {
  word-wrap: normal;
  overflow: auto; /* maybe */
}
```

**Comment by tmeasday** [comment]
Hey @lirbank - sorry took a while to get here. Did you already fix the README on your package?

**Comment by domyen** [comment]
Hey @lirbank this is an intentional tradeoff to address variable screen sizes without needing to horizontal scroll through code snippets. 

The reading experience should be improved with syntax highlighting refinement.
https://github.com/percolatestudio/atmosphere-beta/issues/36#issuecomment-49090816
