### ISSUE TITLE
Feedback overlay possibly needs some description

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#143]
The context of the feedback button when viewing a package can easily be confused for feedback for _that particular package_ and **_not**_ atmosphere. (example: #142)

**Comment by dburles** [comment]
@dominicnguyen hey any thoughts?

**Comment by domyen** [comment]
Since the feedback button lives in the global menu area, I'm not too concerned about folks getting confused. Let's keep an eye on it. As far as I know #142 was the first mistaken feedback for a package that we received in 3 months. 

p.s., we're also removing this element with the accounts/oauth sprint.
