### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by dburles** [percolatestudio/atmosphere#145]
Still seeing timeouts occasionally

```
504 Gateway Time-out
The server didn't respond in time.
```

**Comment by tmeasday** [comment]
I think we were seeing some server trouble. @Zol - any ideas?

**Comment by zol** [comment]
@tmeasday - yeah, I was looking into this on the weekend. The number of times atmos becomes unresponsive due to CPU is increasing, although according to GA our traffic isn't increasing significantly. Something smells shlemielly.

My initial suspicions are the cron job - sometimes it takes a long time to run although it shouldn't run that often.

It would be good to rule out our re-curring code (calculating stats) before looking closer at pubs.

CPU on db is negligible except for a spike when the cronjob runs each night. It's probably time to get together and think about a strategy.
