### ISSUE TITLE
Rate and comments

### ISSUE THREAD

**Issue by Vadorequest** [percolatestudio/atmosphere#182]
I would love to have a rating system such as comment for Meteor packages.
There are sometimes several packages to basically do the same thing and having this kind of info would help a lot to do the right choice.

**Comment by tmeasday** [comment]
Yes! Definitely. This is on our roadmap..

**Comment by Vadorequest** [comment]
Okay! Nice ;)

**Comment by domyen** [comment]
Roadmap visible here https://trello.com/b/RDZR8YGF/atmosphere-product-roadmap

**Comment by dandv** [comment]
Since comments are not implemented, can we keep this issue open?

**Comment by tmeasday** [comment]
Is there any point given the roadmap?

**Comment by dandv** [comment]
1. To me (and probably others), closed issues signify they are solved.
2. The flightpath roadmap is less known than this GitHub repo (I might be wrong on this one).
3. Hyperlinking works better on GitHub (See my link to @jagi's repo above).

**Comment by Vadorequest** [comment]
I agree with Dan.

**Comment by lukejagodzinski** [comment]
Would be great to have it. Of course there is a risk that it could transform into Q&A forum.

I would see it in the form similar to the comments on Google Play. Where you can choose version, which the comment refers to.

It could be also good idea to add tags or category to the package, so that it would be easier to search for the tools from the given area.
