### ISSUE TITLE
Is atmosphere abandoned?

### ISSUE THREAD

**Issue by enricribas** [percolatestudio/atmosphere#191]
The site doesn't work. No packages show up. The repo is missing. No one seems to reply to issues. Have I missed something?

**Comment by domyen** [comment]
Hey @enricribas, you can reach out to us here or on twitter [@atmospherejs](twitter.com/atmospherejs). One of our webservers was causing a service issue for a small percentage of users and needed to be restarted. We're all good now.

If you have a bug please forward a way to reproduce or give more details on what the problem is so we can fix it quickly. Apologies for the inconvenience.
