### ISSUE TITLE
My package doesn't show the README even though the GitHub link works

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/atmosphere#249]
My new package, simple:katex, doesn't show the README on the page, even though the GitHub link works : https://atmospherejs.com/simple/katex

**Comment by tmeasday** [comment]
This happens when the github URL redirects (from https://github.com/stubailo/katex/ to https://github.com/stubailo/meteor-katex in your case). GitHub's API returns a 404 to us in that case, we can't differentiate from a missing readme.

The solution is to update your package to have the updated GH URL.
