### ISSUE TITLE
Missing package versions

### ISSUE THREAD

**Issue by rgoomar** [percolatestudio/atmosphere#257]
The information for this package: https://atmospherejs.com/rgoomar/contactform is not updating. 

Here is the `package.js` file: https://github.com/rgoomar/contactform/blob/master/package.js

I have tried both the URL with .git and without it and checked for redirect issues... but nothing is working.

Anyone else having this problem?

**Comment by domyen** [comment]
@tmeasday do we have any tests for getting package readmes from Github? It'd be good to have a suite of test packages to reference in cases like this.

**For example:**
1. With Github URL
   - Correct format
   - Incorrect format
2. Without Github URL

**Comment by parhelium** [comment]
I have the same issue with package [parhelium:templating-ractive](https://atmospherejs.com/parhelium/templating-ractive).

Package.js : https://github.com/parhelium/package-templating-ractive/blob/master/package.js

**Comment by tmeasday** [comment]
@parhelium - in your case the issue is that your package doesn't have a git URL set. You can see this because there are no "git" and "issue" links on the package page.

@rgoomar - for some reason we don't have any versions of your packages synced. Not sure what's happening there as a I can see them in `meteor show`. I'll investigate further.

@dominicnguyen - not quite sure what you are imagining here? I think we could definitely show some better information in the readme area to differentiate some of these cases (1. no version, 2. no git on latest version, 3. README not found). 

However in case 3 I'm not sure how easily we can tell the difference between redirects and otherwise. It seems like a bug with GH's API really.

**Comment by parhelium** [comment]
@tmeasday I set `git` field with proper url in package.js

```
Package.describe({
  name:'parhelium:templating-ractive',
  summary: "Allows ractive templates to be defined in .ract files",
  version: "0.6.0_2",
  git:'https://github.com/parhelium/package-templating-ractive'
});
```

What I'm doing wrong ?

**Comment by tmeasday** [comment]
@parhelium - right, I'm sorry. I think it's the same problem as @rgoomar then, mysterious missing package versions. I think it's due to the `_X` at the end of the package version perhaps. Investigating.

**Comment by parhelium** [comment]
I forgot to set git url in version `0.6.0` but did that in `0.6.0_1` and `0.6.0_2`.

**Comment by tmeasday** [comment]
Ok, figured it out upstream. All three packages seem good now.

**Comment by rgoomar** [comment]
Thanks @tmeasday!

**Comment by parhelium** [comment]
Thanks @tmeasday
