### ISSUE TITLE
Search by username/org name should also show repositories

### ISSUE THREAD

**Issue by brentjanderson** [percolatestudio/atmosphere#26]
It appears that the search function only supports searching by repository name. Searching by tags, repository owner/org (e.g. percolatestudio), or ReadMe contents would be enormously helpful when searching for packages.

**Comment by tmeasday** [comment]
Going to close this and deal with it as part of #49

**Comment by tmeasday** [comment]
I've improved the search to search author names (e.g. "Zoltan Olah"). It doesn't pick up names in the github URLs or readmes as yet. 

The reason is that because the search isn't very smart yet (just uses a full-text search, not an index or relevance or anything like that), searching these would lead to a lot of false positives.
