### ISSUE TITLE
Another set of packages without GitHub links?

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#276]
Seems like everyone and their dog has a `pattern to display application errors to the user`:
https://atmospherejs.com/?q=error

=>
https://atmospherejs.com/tmeasday/errors
https://atmospherejs.com/sotu/errors
https://atmospherejs.com/chappo/errors
https://atmospherejs.com/tomwasd/errors
https://atmospherejs.com/mrt/errors
https://atmospherejs.com/fsoroush/errors
https://atmospherejs.com/vstross/errors
https://atmospherejs.com/lezed1/bootstrap-errors
https://atmospherejs.com/asp149/errors

How do I get one? :-)

https://atmospherejs.com/robsw/errors is another one, with a blank README?

**Comment by domyen** [comment]
From a quick look at the handful of packages linked here the authors haven't posted a readme to Github and thus Atmosphere is unable to retrieve one. Is this a bug with Atmosphere or a suggestion about some type of readme enforcement/prompting?

**Comment by udondan** [comment]
The source of the problem is more that the github reference got lost during package migration. If I remember correctly the github link was an absolute requirement to publish a package with mrt before, right? Was it an accident or intended that this information got lost during migration?

I couldn't find the repos for most of the packages but the one from @lezed1 is the perfect [example](https://github.com/lezed1/meteor-bootstrap-errors/blob/master/smart.json#L7), just in case this problem was unknown to you. :) I had to fix this in all my packages and wonder why the git url was not migrated along with the other info from the smart.json.

**Comment by dandv** [comment]
@dominicnguyen, are these _real_ packages? Why would there be so many packages to do apparently the same thing? What if the migration process crated some kind of phantom entries?

**Comment by dandv** [comment]
CC @fsoroush, @tomwasd, @vstross, @sotu, @chappo, @asp149

**Comment by dandv** [comment]
As seen above, some of these users are no longer on GitHub, let alone have those repos.

**Comment by tmeasday** [comment]
@dandv the explanation for this set of package is that in Discover Meteor we have a example "publishing a package" chapter where we publish this particular package.

@udondan you are correct -- because previously a git repo was a requirement, almost all packages had a readme. This isn't going to be the case now.

**Comment by dandv** [comment]
@tmeasday: any chance to remove these example packages? They seriously clutter the search results, and I bet the authors won't mind.

**Comment by tmeasday** [comment]
@dandv we aren't in control of the package repository any more :)

We added flagging for just this purpose! Flag away!

**Comment by queso** [comment]
Does an author get alerted before a flagged package is removed? Or do we just arbitrarily do whatever?

**Comment by tmeasday** [comment]
Flagged packages aren't removed, just penalized in rankings and "flagged" in the UI.

Right now we don't notify the author (chances are we don't know anything about them), but they can easily remedy the problem by publishing a new version, which is probably what's needed anyway if a package has been flagged.
