### ISSUE TITLE
Package still registers version despite meteor publish error

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#285]
Not sure if this belongs here or on meteor (CC @ekatek):

I've just published a package called [caret-position](https://atmospherejs.com/dandv/caret-position). On the first attempt to publish, I got an error that the version (2.1.0_1) already existed. Incremented the patch level to 2.1.1 and `meteor publish`ed again. Success.

However, both versions appear at https://atmospherejs.com/dandv/caret-position. Here's the log:

``` bash
21:56:27 [1s] dan:~/meteor-caret-position$ meteor publish
Reading package...
Bundling source...
Creating package version...
Error creating package version: Version already exists

21:57:31 [10s] dan:~/meteor-caret-position$ ... edit file, commit , git push -f ...

21:57:40 [2s] dan:~/meteor-caret-position$ meteor publish
Reading package...
Bundling source...
Creating package version...
Uploading source...
Publishing package version...
Bundling build...
Creating package build...
Uploading build...
Publishing package build...
Published dandv:caret-position, version 2.1.1

Done!
```

**Comment by ekatek** [comment]
I am not quite sure what the bug is -- both sources (atm & meteor) are in
agreement that the version exists. Basically, the behavior you are seeing
does seem consistent with the version existing -- are you sure that the
version does not exist? (I mean, yes, presumably, but got to check!) Can
you add it to an app with @= or somesuch? Also, what version of meteor are
you using?

If you are sure, then, that's interesting.  I can try to look into it
tomorrow.

**Comment by dandv** [comment]
@ekatek: there was a ["2.1.0-1" version](https://github.com/dandv/meteor-caret-position/commit/00e965885dbbdc6d64cc495e61985dd2312723e0) (dash vs. underscore) but I presume the difference is irrelevant and the last "1" was interpreted as the wrapper version number.

PS: would help to add some contact details to your GitHub profile so folks can be sure you're with MDG :)

**Comment by tmeasday** [comment]
@dandv did you figure this one out?

**Comment by dandv** [comment]
@tmeasday, yes, closing.
