### ISSUE TITLE
Untraceable packages

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#306]
With `mrt`, there had to be a valid git repo for a package to get published.

With the new Atmosphere, the `git` field is optional and worse, can be completely different from the actual repo of the app. Combined with user apathy in filling in their MD account profile information, this makes it impossible to reach out authors of forks that pollute Atmosphere.

Who cares? Well, take a look at this search:

https://atmospherejs.com/?q=publish

Nearly 20% of the results are _knowingly_ test or junk. (`junk:bla` takes the cake)

Let's say we wanted to reach out to these folks. Take a look at [david](https://atmospherejs.com/david). There's no information whatsoever about his test package. Google searches for the names of his other packages reveal nothing (maybe he deleted the repos?) Even with flagging, this leaves completely pointless packages in the search results.
### Proposed solutions
- Add a "Contact author" button to email the publisher of the package, visible only to moderators if need be. Since there is an MD account associated with Atmosphere, and that MD account had to be confirmed with an email, this is feasible.
- Have a request queue where MD or Atmosphere admins can speedy delete junk packages, similar to the mechanism employed by Wikipedia or StackOverflow

BTW any plans for open sourcing Atmosphere? I'd love to submit PRs for things like these.

**Comment by dburles** [comment]
Hey @dandv unless the user has signed into Atmosphere we don't have any record of their account. So in that case you could contact MDG directly.

In general it's inevitable that there will be some "junk" packages and we have some measures in place that can help to make it clear what is junk, and what isn't (e.g. stars/flags combined with coming improvements to the search etc). We're always looking at ways to improve things in that manner. So for now, this is the path we're focused on rather than a moderated setup.

There aren't as yet any plans to open source Atmosphere.

**Comment by zol** [comment]
We're going to fix this by adding moderator capabilities to certain users and having their flagging power multiplied by some factor that will be enough to eliminate junk packages.

**Comment by dandv** [comment]
:+1:

**Comment by zol** [comment]
@tmeasday I've started this on `306-moderators`. On second thoughts, moderator flagging could just set `'latestVersion.flagged': true` in `'Flags.insert'`. After looking closer at the code, my earlier suggestion seems kind of cumbersome to implement.

**Comment by tmeasday** [comment]
@zol - I don't think that'll work because in the next `checkFlaggedPackages` it'll just become `flagged: false` again, due to the flag count being too low. I'd suggest instead checking for a flag by a moderator (perhaps store a `moderator` field on the flag itself?) in `checkFlaggedPackages`, and short circuiting the counting logic in that case.

**Comment by zol** [comment]
Got it, that makes sense. And I think I know the answer but there's no sense in trying to set the `flagged: true` state immediately right? (i.e we can afford to wait till the end of the day when `checkFlaggedPackages` runs as the moderator will see the package as flagged in the UI immediately anyway)

**Comment by tmeasday** [comment]
I think there's sense in it if we think it has immediate value to other users for the package to be flagged right away.

But I'd be inclined to keep things simple and just wait for the cron job. Considering your second point :)

**Comment by zol** [comment]
Please review commit c45337e

**Comment by tmeasday** [comment]
Looks great!

**Comment by zol** [comment]
Deployed.

**Comment by dandv** [comment]
Will this work retroactively on flags that the moderators have raised before the system went into effect?

**Comment by zol** [comment]
Unfortunately not.
