### ISSUE TITLE
Discussion re external DDP requests

### ISSUE THREAD

**Issue by gadicc** [percolatestudio/atmosphere#337]
Hey, regarding decision to deprecate external DDP requests in favor of the REST API... obviously I'll respect any decision made by the team since it's your prerogative, but was hoping we could discuss some pros and cons too :)

Obviously one of Meteor's core features is instant reactive updates.  Although, understandably, less regular updates are often a fair trade for better overall performance.  Having said that:
1. How often is it ok to use the endpoint?  Every 10 mins?  Every hour?  Especially given that currently no filtering is possible and the current size is 1.5M.  Is the endpoint a real time query, is it cached, is it pre-generated, is it served via Meteor or a proxy, from RAM / disk etc?
2. Is constant polling that much less resource intensive than "responsible" live queries?  Given that Meteor's reactivity is pretty efficient, and for the fview example, we subscribe to a search and about 10 packages.

I mention all this since I really love Meteor's instant updates, and I wonder if an additional, alternative solution is to simply have resource limits for registered users.  This is something I'm also prepared to work on if it's something you're open too.

**Comment by splendido** [comment]
I'm interested on this too...

Taking inspiration from what @gadicc did, I'm publishing stars and install counts for useraccounts packages on [this page](http://useraccounts.meteor.com/)

my DDP subscription to atmosphere is [here](https://github.com/meteor-useraccounts/website/blob/master/server/atmosphere.js) and is done on the server.

I appreciate that it might be better made on the client side (so that when there are no clients connected there are no active subscriptions...), but IMHO that's not much different from connecting to atmosphere and make a search there (which could be the result of a link click from another page)

This said I'll also accept any decision taken from your side.

**Comment by zol** [comment]
Hey @gadicc and @splendido . There are a couple of things going on here.
1. We recently updated the search code to use solr, which we're now running on our database machine. The current search publication that you guys are using is based off the old mongodb-regex based solution that we used to have and are now phasing out due to terrible performance. This is the main impetus for shutting down that particular publication - there is just no reason for us to backport our solr solution which is method call based and heavily optimized (we only send the data down that you can see on the search results page).

Furthermore, the regex publication you guys have been using is non-reactive anyway, so subscribing to it really makes no sense as you'll never receive any updates beyond the initial set of documents. The open subscription will just end up chewing up resources (albeit not a lot) at both our end and yours.
1. Regarding using DDP pubs as APIs. I agree, this would be fantastic. Sadly, in the current state of the world we don't have good tooling for logging, rate limiting and performance analysis of the Meteor pub/sub model. This is already tricky to deal with at an application level, where we control exactly how our publications are used and can reason about the performance impact a single user may have on our servers. From an API standpoint, it would be really easy to use the API in ways that we haven't intended for and due to the lack of tooling it would be hard for us to detect or prevent this kind of usage. It's fairly easy for people to innocently use create subscriptions with devastating consequences, for instance, one time someone built an app that opened a subscription to every single package.

I guess the take-away is that our REST API is not intended to be realtime. What sort of solution are you looking for? For instance, fastosphere downloads our package list and indexes it once a day (a use case our new api is really intended for). If your goal was to display the most current data for a list of packages at the time a user visits your site, we would look at supporting this with a list of package names you can pass in to the API call that would filter the list down (rather than getting the entire 1.5mb set). You could then make a call to this on every pageview. Would that help?

**Comment by gadicc** [comment]
Hey @zol, thanks for the quick reply.  It's really helpful to know what's happening behind the scenes over at Atmosphere, and of course, with your detailed explanation (appreciated), DDP does indeed not make much sense in this case.  So even though I'd be eager to help with tooling for a DDP API, it's a moot point here.

Ok, so with the above in mind, I'm perfectly happy using the REST API.  Maybe with a 10m debounced query on user connect until the filter/query API is available, after which time I'd feel more comfortable using much smaller debounced limit.

Thanks!

**Comment by zol** [comment]
@gadicc no worries and thanks for adapting your code for us, I realize its probably a pain. I'll let you know as soon as I've added the filtering options to the API, after which point I'm not too worried about your frequency of requests.

**Comment by gadicc** [comment]
All good, it's only a few lines of code.  My bigger concern was the "realtime" factor, which has been adequately addressed.  Thanks again :)

**Comment by splendido** [comment]
Yeah, this all makes sense now.
I'll adapt my code too without any worries nor concerns ;-)

Thank you @zol for the comprehensive explanation!

**Comment by splendido** [comment]
@zol, am I wrong or there's no download count nor stars count within the JSON data you can get with the REST API at https://atmospherejs.com/a/packages?

...getting this counts might be the only reason to use it ;-)

**Comment by splendido** [comment]
wooops! I'm sorry!
I've noticed only now that you get both `starCount` and `installs-per-year`.

Please don't consider the previous post and feel free to delete both!

Tnx

**Comment by zol** [comment]
Hey @gadicc and @splendido . I've just deployed the extra API endpoint `findByNames` to query for metadata for a list of packages (see the [faq](https://atmospherejs.com/i/faq)). You don't need to worry too much about hitting this endpoint too often. Enjoy :)

**Comment by splendido** [comment]
Thanks a bunch @zol!
...already deployed ;-)

See [this file](https://github.com/meteor-useraccounts/website/blob/master/server/atmosphere.js)

Is hitting the endpoint every hour fine? Does it make sense?

**Comment by zol** [comment]
Nice work, that was quick. Yup, hitting it every hour is totally fine!

**Comment by splendido** [comment]
Ok, tnx!

Keep up the good work! :-)

**Comment by gadicc** [comment]
Amazing!  Thanks @zol, appreciated.  And thanks @splendido for sharing the code :)
