### ISSUE TITLE
Syntax Highlighting on Code Snippets

### ISSUE THREAD

**Issue by hharnisc** [percolatestudio/atmosphere#36]
In the README markdown it would be easier to digest code snippets if they had some syntax highlighting.

**Comment by yasinuslu** [comment]
+1

**Comment by Nemo64** [comment]
Just Released my first package and stumbled over this too.
The css classes are already there, they would just need a few css colors.

**Comment by dandv** [comment]
+1. Tried both ```js and ```javascript but no highlight.

**Comment by hharnisc** [comment]
This has done the trick for syntax highlighting, and it's been very easy to integrate (MIT like license too):

https://github.com/isagalaev/highlight.js

**Comment by domyen** [comment]
Done. @tmeasday check it out on this page http://localhost:3000/package/Mobi-Router. 
Ended up with a simple CSS solution that piggybacks on Githubs already processed markup. If your code is highlighted on Github it's going to be highlighted here as well.

@hharnisc Thanks for the link. The library seems fantastic! Because Atmosphere uses GH Readme's, which are passed through their own server-side syntax highlighter, it's not possible to integrate highlight.js

**Comment by hharnisc** [comment]
Seems like an elegant solution to the problem either way. Looking forward to seeing this in production!

**Comment by timbrandin** [comment]
+1
