### ISSUE TITLE
Package History Incomplete

### ISSUE THREAD

**Issue by softwarerero** [percolatestudio/atmosphere#361]
I started https://atmospherejs.com/softwarerero/accounts-t9n in February 2014 with version 0.0.1. However the history on atmosphere starts with 0.0.17 in September 2014. I guess I made a mistake when migrating the package. Can I correct this?

**Comment by tmeasday** [comment]
Hey @softwarerero,

I think the older versions are attached to the mrt:accounts-t9n package. This happened because we didn’t have your meteor developer account in time for the automatic migration.

Probably you should add something to the github readme to indicate to people that they should install the newer version so it shows up here: https://atmospherejs.com/mrt/accounts-t9n

Then possibly you could mark that older package unmigrated. You should link your accounts at atmosphere.meteor.com/accounts and I can give you ownership over the mrt: package.

**Comment by softwarerero** [comment]
Thanks. I see what happend. I assigned my Atmosphere account to another Meteor Developer account. Can I change this or add a second one?

**Comment by tmeasday** [comment]
If you have access to the other MD account I think that'll be fine. As long as you can login as that developer you can mark the package as unmigrated (i.e. hide it in atmosphere).

**Comment by tmeasday** [comment]
Let me know what that account is and I'll give it access.

**Comment by softwarerero** [comment]
My Atmosphere account 'softwarerero' is connected to the Meteor account 'sun', but the package accounts-t9n belongs to 'softwarerero'.

**Comment by tmeasday** [comment]
I've added you as a maintainer on the old package. You may now do what you like if you `meteor login` as `sun`. You can't rename packages, so generally people tend to just clearly message what the new package called and mark the old package as unmigrated.

**Comment by softwarerero** [comment]
Done. Thanks.
