### ISSUE TITLE
Odd SEO / Google search result

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#366]
A Google search for "aws weibo account" returns https://atmospherejs.com/packages/service%2520for:

![image](https://cloud.githubusercontent.com/assets/33569/7113264/e670283c-e186-11e4-9844-96e1633fe17f.png)

**Comment by tmeasday** [comment]
Thanks for the report @dandv.

This seems to be a problem with the sitemaps package we are using. When URLs have a ' ' in them, it seems to be outputting (for example):

```
  <url>
    <loc>https://atmospherejs.com/packages/oplog%2520tailing</loc>
    <lastmod>2015-04-13T00:05:18+00:00</lastmod>
    <changefreq>daily</changefreq>
    <priority>0.8</priority>
   </url>
```

**Comment by tmeasday** [comment]
Ok, so the issue is that iron:router escapes the URL paths that come out of `Router.path()` (in this case to `"/packages/Service%20for"`) then gadicohen:sitemaps escapes the URLs a second time (to `"/packages/Service%2520for"`, which is what google indexes) . 

Double escaping! Blurgh. @zol any thoughts on a good solution here? We could call `unescape()` on the path we get out of IR I guess?

**Comment by zol** [comment]
Urghh. @tmeasday I guess we could unescape it. A PR to IR with an option to not escape the path would be better though. I can't think of a better solution.

**Comment by tmeasday** [comment]
No way to do it w/ IR right now. PR is too much of a PITA. Will just do it manually.

**Comment by zol** [comment]
Deployed and checked:

```
<url>
<loc>https://atmospherejs.com/packages/oplog%20tailing</loc>
<lastmod>2015-04-17T20:40:45+00:00</lastmod>
<changefreq>daily</changefreq>
<priority>0.8</priority>
</url>
```
