### ISSUE TITLE
Mechanism to unmigrate packages that their authors can no longer un-migrate

### ISSUE THREAD

**Issue by dandv** [percolatestudio/atmosphere#386]
[Here](https://github.com/halilertekin/meteor-materialize/issues/2) ([archive](https://web.archive.org/web/20150523111312/https://github.com/halilertekin/meteor-materialize/issues/2)) is a discussion that showcases the usefulness of unmigrating flagged packages. TL;DR: the original author no longer has a GitHub account, or is otherwise unable to unmigrate the package due to acts of God or whatnot. We currently have no mechanims to prevent these abandoned and defective packages from cluttering search results.

This of course would require a high level of consensus.

CC fellow moderator @splendido.

**Comment by splendido** [comment]
I guess there's no way to delete/unmigrate a package from atmosphere,  since this is something to be dealt with on the MDG's packages server using _meteor_ API.

This said, as a first tool it might be helpful to have  a moderators group to mention inside issues OP so to cc others moderators and collect a consensus about flagging an old package.
Perhaps something like @percolatestudio/atmosphere-mod?

In some edge cases pinging the poin of view of other moderators might help taking the decision to flag a package...

...from what I understood,  a flag by a MOD should be enough to hide the package on atmosphere,  isn't it?

**Comment by splendido** [comment]
In this specific case, the package [halil:materialize](https://atmospherejs.com/halil/materialize) appears to me as flagged (I actually flagged it...).
Do you think it would be useful to have a different flag simbol to be used for MOD flags?
...at least for moderators to get a feed-back about what they flagged and whatnot...

![mod-flag](https://cloud.githubusercontent.com/assets/6148980/7784609/f3387f56-016b-11e5-9727-dea305772380.png)

**Comment by dandv** [comment]
> a flag by a MOD should be enough to hide the package on atmosphere, isn't it?

Nope, that's how I found out about that halil package.

A flagged package shows up flagged, but it still clutters the search results. Arguably, that's to prevent MOD abuse, but if two mods flag a package, and X period of time elapses without the flag being addressed, it would be useful to be able to unmigrate it.

**Comment by splendido** [comment]
Ok, I see.

...perhaps 5 MOD flags should be enough to ring the bell at MDG's HQ ;-)

**Comment by tmeasday** [comment]
Hey guys,

Thought about this a bit. I think it's best if Atmosphere remains as thin a wrapper around the source of truth for packages (i.e. MDG's servers) as possible. So for instance, we shouldn't hide flagged packages (#360), and we shouldn't auto-unmigrate packages. 

Not to say I think it's a bad idea to unmigrate such dead packages at their end. (TBH I'm of two minds about it, but don't have a strong opinion). Sorry if that's a cop-out.
