### ISSUE TITLE
Do you plan to open source atmosphere-beta ?

### ISSUE THREAD

**Issue by yasinuslu** [percolatestudio/atmosphere#54]
It would be a huge help to the community if you release it's source code :)

**Comment by queso** [comment]
:+1:

**Comment by tmeasday** [comment]
Yes we do! I'm not 100% sure on the timing, probably very soon!

**Comment by yasinuslu** [comment]
Great to hear that @tmeasday. Thanks for all your help to the community.

**Comment by dandv** [comment]
:+1:! I was most curious about the extremely fast search (v1 was quite slow, and it loaded the entire collection of packages on the client). Seems like a pub/sub autocomplete package could be factored out, because the two we have right now do autocompletion only on the client - [typeahead](https://github.com/sergeyt/meteor-typeahead/issues/4) and [autocomplete](https://github.com/mizzao/meteor-autocomplete/issues/6).

**Comment by petermikitsh** [comment]
Is there still a plan to open source the code? It's a great site.

**Comment by tmeasday** [comment]
I guess it wasn't very soon. :(

Sorry it's taken a while. We'll probably just try and get as much as possible into packages that people can use rather than O/S-ing the entire site. 

In the meantime if there are any particular features you'd like to know more about we can post about them like: http://blog.percolatestudio.com/engineering/atmosphere-score/

Thanks btw @petermikitsh

**Comment by dandv** [comment]
Looks like the main issue tracking open sourcing Atmosphere is #219.

**Comment by queso** [comment]
Both are closed and I don't really see this happening any time soon (if at all with native NPM support coming)

**Comment by petermikitsh** [comment]
Atmosphere will probably still be around for awhile. It will take some time to fully transition to 100% NPM.

**Comment by queso** [comment]
I'd be willing to bet big money it will never be open source ;)
