### ISSUE TITLE
Provide a way to browse all packages

### ISSUE THREAD

**Issue by hellotoby** [percolatestudio/atmosphere#84]
Please provide a way to browse all packages. 

This helps a lot when you kind of know what you want, but aren't sure of the keywords to search for.

**Comment by serkandurusoy** [comment]
I'd like to be able to see a list of all available packages as well, but also be able to sort them (date, name, publisher).

I browse atmosphere almost daily to see what's new! And scroll all the way down every once a couple of weeks to remind me of what can be done, what has already been done so that I get some ideas about my app, or perhaps new apps.

The old atmosphere used to provide a means to discover all packages to see what's out there. And the new atmosphere is point blank lacking that :(

**Comment by willemx** [comment]
+1
Just a simple boring list like in the old atmosphere would be fine. No fancy makeup needed for this feature, just display as much items as will fit on the screen.

**Comment by vectorselector** [comment]
yes, it's rather frustrating not to be be able to browse all packages. maybe i just find it amusing to check out what someones ideas are or were. i can see if a package has been recently updated and maintained, but that's not the only pleasure in life you know :)

**Comment by tmeasday** [comment]
FYI you can now do this at http://atmospherejs.com/recent
