### ISSUE TITLE
Bitbucket-hosted package has no links

### ISSUE THREAD

**Issue by rdickert** [percolatestudio/atmosphere#88]
I was checking out packages that add an editor and found the package [sp-epic-editor](http://beta.atmospherejs.com/package/sp-epic-editor).  I was confused when I couldn't get to the github page from the Atmosphere page. Turns out, it's hosted on bitbucket, and Atmosphere doesn't provide buttons to find the repo, whereas a github-hosted project has both a "Github" and a "Report Bugs" link. If Bitbucket is supported, similar buttons would be nice. If not, some kind of notification that it's a non-github source (or even disabled github buttons) would improve UX – so people don't stare at the page trying to remember where the link is.

**Comment by domyen** [comment]
We'll take these good suggestions onboard when we tackle edge cases like this. Since we're focussing most of our efforts on Github, Bitbucket isn't supported at this time but perhaps will be in the future. 

Example packages that aren't on GH for future reference:
- (ms-seo)[http://beta.atmospherejs.com/package/ms-seo]
- (sp-epic-editor)[http://beta.atmospherejs.com/package/sp-epic-editor]

**Comment by domyen** [comment]
Closing this. Our roadmap is tracking this feature. https://trello.com/c/zdd3oQ8s/11-bitbucket-support
